/** Four everyday Finnish recipes so the app is usable on first run. */
export const SEED_RECIPES = [
  {
    title: "Lohikeitto",
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 25,
    tags: ["kala", "arki", "keitto"],
    ingredients: [
      "400 g nahatonta lohifileetä",
      "600 g kiinteitä perunoita",
      "1 sipuli",
      "1 porkkana",
      "8 dl vettä",
      "1 kalaliemikuutio",
      "2 dl kermaa",
      "5 maustepippuria",
      "1 laakerinlehti",
      "½ nippua tilliä",
      "suolaa",
    ],
    steps: [
      "Kuori ja kuutioi perunat ja porkkana. Hienonna sipuli.",
      "Kiehauta vesi, liemikuutio, maustepippurit ja laakerinlehti. Lisää perunat, porkkana ja sipuli ja keitä n. 15 min, kunnes perunat ovat melkein kypsiä.",
      "Paloittele lohi ja lisää keittoon kerman kanssa. Hauduta miedolla lämmöllä 5–7 min, kunnes lohi on kypsää.",
      "Mausta suolalla ja lisää hienonnettu tilli juuri ennen tarjoilua.",
    ],
    notes: "Classic Finnish salmon soup. Ruokakerma works if you want it lighter.",
  },
  {
    title: "Jauhelihakastike ja perunat",
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 30,
    tags: ["arki", "nauta"],
    ingredients: [
      "800 g perunoita",
      "400 g jauhelihaa",
      "1 sipuli",
      "1 rkl rypsiöljyä",
      "2 rkl vehnäjauhoja",
      "4 dl vettä",
      "1 lihaliemikuutio",
      "1 dl kermaa",
      "1 tl suolaa",
      "½ tl mustapippuria",
    ],
    steps: [
      "Keitä perunat suolalla maustetussa vedessä kypsiksi (n. 20 min).",
      "Ruskista jauheliha ja hienonnettu sipuli öljyssä.",
      "Ripottele jauhot pinnalle ja sekoita. Lisää vesi ja liemikuutio ja anna kiehua 10 min.",
      "Lisää kerma, mausta suolalla ja pippurilla. Tarjoa perunoiden kanssa.",
    ],
    notes: null,
  },
  {
    title: "Broilerikastike",
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 20,
    tags: ["arki", "kana", "quick"],
    ingredients: [
      "400 g maustamattomia broilerin suikaleita",
      "1 sipuli",
      "1 punainen paprika",
      "1 rkl rypsiöljyä",
      "1 tl paprikajauhetta",
      "2 dl ruokakermaa",
      "1 dl vettä",
      "1 kanaliemikuutio",
      "suolaa ja pippuria",
      "3 dl riisiä",
    ],
    steps: [
      "Keitä riisi pakkauksen ohjeen mukaan.",
      "Ruskista broilerin suikaleet öljyssä. Lisää hienonnettu sipuli ja paprika ja kuullota hetki.",
      "Lisää paprikajauhe, vesi, liemikuutio ja ruokakerma. Hauduta 10 min.",
      "Mausta suolalla ja pippurilla ja tarjoa riisin kanssa.",
    ],
    notes: null,
  },
  {
    title: "Kasviscurry",
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 25,
    tags: ["vegetarian", "quick", "kasvis"],
    ingredients: [
      "1 sipuli",
      "2 kynttä valkosipulia",
      "1 rkl inkivääriä raastettuna",
      "1 bataatti",
      "1 rkl rypsiöljyä",
      "2 rkl currytahnaa",
      "1 tlk (400 g) kikherneitä",
      "1 tlk (400 ml) kookosmaitoa",
      "1 tlk (400 g) tomaattimurskaa",
      "100 g babypinaattia",
      "suolaa",
      "3 dl riisiä",
    ],
    steps: [
      "Keitä riisi pakkauksen ohjeen mukaan.",
      "Kuullota sipuli, valkosipuli ja inkivääri öljyssä. Lisää currytahna ja paista minuutti.",
      "Lisää kuutioitu bataatti, valutetut kikherneet, kookosmaito ja tomaattimurska. Hauduta 20 min.",
      "Sekoita joukkoon pinaatti ja mausta suolalla.",
    ],
    notes: null,
  },
];
